# Generated by Django 3.0.7 on 2020-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1sheet', models.CharField(max_length=250)),
                ('file1column', models.CharField(choices=[('1Sheet1col1', '1Sheet1col1'), ('1Sheet1col2', '1Sheet1col2'), ('1Sheet2col1', '1Sheet2col1'), ('1Sheet2col2', '1Sheet2col2')], max_length=250)),
                ('file2sheet', models.CharField(choices=[('2Sheet1', '2Sheet1'), ('2Sheet2', '2Sheet2')], max_length=250)),
                ('file2column', models.CharField(choices=[('2Sheet1col1', '2Sheet1col1'), ('2Sheet1col2', '2Sheet1col2'), ('2Sheet2col1', '2Sheet2col1'), ('2Sheet2col2', '2Sheet2col2')], max_length=250)),
            ],
        ),
    ]
