# Generated by Django 3.0.7 on 2020-06-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
